#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 08 23:45:48 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Sildur's Vibrant Shaders v1.56 Extreme.zip
